name = "HelloWorld"
uuid = "91c3276f-7c05-4a0b-8cd8-05eb63f659ae"
authors = ["Miguel A. Jimenez-Urias"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
